#!/usr/bin/env bash
. "$(git --exec-path)/git-sh-setup"
require_clean_work_tree pull

__branch=$(git rev-parse --abbrev-ref HEAD)
__branch=${1:-$__branch}
__upstream=${2:-upstream}

git fetch --tags --prune --all
git pull $__upstream $__branch && git push origin $__branch
