#!/usr/bin/env bash
. "$(git --exec-path)/git-sh-setup"
require_clean_work_tree checkout

# Read custom script settings
__top_level=$(git rev-parse --show-toplevel)
if [[ -f "${__top_level}/.git-scripts-config" ]]; then
  . "${__top_level}/.git-scripts-config"
fi

# PROJECT_PREFIX can be set on config file OR environment variables
__project_prefix="${PROJECT_PREFIX}"

__owner_regex="s/(.+):([a-zA-Z0-9]+)\/([a-zA-Z0-9-]+)\.git/\2/"
__upstream_owner=$(git remote -v | grep upstream | grep fetch | awk '{print $2}' | sed -E "${__owner_regex}")
__fork_owner=$(git remote -v | grep origin | grep fetch | awk '{print $2}' | sed -E "${__owner_regex}")
__base_branch=""
__type=""
__ticket=""
__title=""

checkout_base_branch() {
  printf "\n\n* Checking out base branch...\n"

  PS3="Select a number or type a branch name: "
  select choice in "develop" "master"; do
    case $choice in
      "master"|"develop")
        __base_branch=$choice
        ;;

      *)
        __base_branch=$REPLY
        ;;
    esac

    break
  done

  git checkout $__base_branch
}

get_ticket_number() {
  printf "\n\n* Asking for ticket number...\n"

  printf "Ticket number: ${__project_prefix}"
  read __ticket
  __ticket="${__project_prefix}${__ticket}"
}

get_task_title() {
  printf "\n\n* Aking for task title...\n"

  printf "Task title: "
  read __title
}

update_with_upstream() {
  printf "\n\n* Updating with upstream...\n"

  git pull-upstream
}

checkout_new_branch() {
  printf "\n\n* Checking out new branch...\n"

  git checkout -b "${__ticket}"
}

create_empty_commit() {
  printf "\n\n* Creating empty commit...\n"

  git commit --allow-empty --message "${__title}"
}

push_to_origin() {
  printf "\n\n* Pushing to origin...\n"

  git push --set-upstream origin ${__ticket}
}

create_pull_request() {
  printf "\n\n* Creating pull request...\n"

  __pr_title="[${__ticket}] ${__title}"
  __pr_message="${__pr_title}"

  hub pull-request -m "${__pr_message}" -b "${__upstream_owner}:${__base_branch}" -h "${__fork_owner}:${__ticket}" -o
}

checkout_base_branch
get_ticket_number
get_task_title
update_with_upstream
checkout_new_branch
create_empty_commit
push_to_origin
create_pull_request

printf "\n\n*** All set! ***\n"
