#!/usr/bin/env bash

__debug=false
__in_background=true
__kill=false
__livereload="-lr false"
__npm_install=false
__partition=""
__pwd=`pwd`
__split=24
__test=false
__translate=false

function run_command() {
  if [[ "$__debug" == true ]]; then
    echo "$@"
  else
    eval "$@"
  fi  
}

# As long as there is at least one more argument, keep looping
while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
        -d|--debug)
        __debug=true
        ;;

        -f|--foreground)
        __in_background=false
        ;;

        -i|--install)
        __npm_install=true
        ;;

        -k|--kill)
        __kill=true
        ;;

        -l|--livereload)
        __livereload="-lr true"
        ;;

        -p|--partition)
        shift
        __partition="$1"
        ;;

        -s|--split)
        shift
        __split="$1"
        ;;

        -t|--test)
        __test=true
        ;;

        --translate)
        __translate=true
        ;;

        *)
        echo "Unknown option '$key'"
        ;;
    esac

    shift
done

if [[ "$__debug" == true ]]; then
  echo "__in_background: $__in_background"
  echo "__kill: $__kill"
  echo "__livereload: $__livereload"
  echo "__npm_install: $__npm_install"
  echo "__partition: $__partition"
  echo "__pwd: $__pwd"
  echo "__split: $__split"
  echo "__test: $__test"
  echo "__translate: $__translate"
  echo ""
fi

run_command "cd /Users/erick.ruizdechavez/Projects/Work/map-ui-ember"

if [[ "$__translate" == true ]]; then
  run_command "python scripts/pseudo_js.py -s app/translations/en/ -d app/translations/"
  exit
fi

if [[ "$__test" == false ]]; then
  run_command "killall ember"

  if [[ "$__kill" == true ]]; then
    exit
  fi

  run_command "rm log/helix.log"
fi

if [[ "$__npm_install" == true ]]; then
  run_command "npm install > /dev/null 2>&1"
fi

if [[ "$__test" == false ]]; then
  __command="ember serve $__livereload"
  if [[ "$__in_background" == true ]]; then
    __command="$__command > log/helix.log 2>&1 &"
  fi
else
  __command="ember exam -c testem.dev.js --reporter dot --split $__split "
  if [[ "$__partition" != "" ]]; then
    __command="$__command --partition $__partition"
  else
    __command="$__command --parallel"
  fi
fi
run_command $__command

run_command "cd $__pwd"
