#!/usr/bin/env bash

if [[ "$3" == "1" ]]; then
  echo "Post Checkout Hook"

  __cwd=$(pwd)
  __top_level=$(git rev-parse --show-toplevel)
  __bower_changed=$(git diff $1 $2 --name-only | grep bower.json -c)
  __package_changed=$(git diff $1 $2 --name-only | grep package.json -c)

  if [[ "$__bower_changed" == "1" ]]; then
    echo "Bower changed"
    cd $__top_level
    bower install
    cd $__cwd
  fi


  if [[ "$__package_changed" == "1" ]]; then
    echo "Package changed"
    cd $__top_level
    yarn
    cd $__cwd
  fi
fi
