#!/usr/bin/env bash
. "$(git --exec-path)/git-sh-setup"
require_clean_work_tree checkout

__cd=/Applications/CocoaDialog.app/Contents/MacOS/CocoaDialog
__current_branch=$(git rev-parse --abbrev-ref HEAD)
__out=$($__cd standard-inputbox --title "Finish Working" --informative-text "Enter branch name to delete, or leave empty to use '$__current_branch'" --string-output --float)
__button=$(echo "$__out" | awk 'NR==1{print}')
__text=$(echo "$__out" | awk 'NR>1{print}')

# Read custom script settings
__top_level=$(git rev-parse --show-toplevel)
if [[ -f "${__top_level}/.git-scripts-config" ]]; then
  . "${__top_level}/.git-scripts-config"
fi

# DEFAULT_BRANCH can be set on config file OR environment variables
__checkout_branch=${DEFAULT_BRANCH:-develop}

if [[ "$__button" = "Cancel" ]]; then
  exit 0
fi

cd $1

__deleting_branch=${__text:-$__current_branch}

if [[ "$__deleting_branch" = "$__current_branch" ]]; then
  git checkout $__checkout_branch
fi

git push origin --delete $__deleting_branch
git branch -D $__deleting_branch;
