#!/usr/bin/env bash
. "$(git --exec-path)/git-sh-setup"
require_clean_work_tree pull

__cd=/Applications/CocoaDialog.app/Contents/MacOS/CocoaDialog
__branch=$(git rev-parse --abbrev-ref HEAD)

# Read custom script settings
__top_level=$(git rev-parse --show-toplevel)
if [[ -f "${__top_level}/.git-scripts-config" ]]; then
  . "${__top_level}/.git-scripts-config"
fi

# DEFAULT_BRANCH can be set on config file OR environment variables
__parent_branch=${DEFAULT_BRANCH:-develop}

__out=$($__cd standard-inputbox --title "Rebase Upstream Branch" --informative-text "Enter upstream branch name or leave empty to use '$__parent_branch'" --string-output --float)
__button=$(echo "$__out" | awk 'NR==1{print}')
__text=$(echo "$__out" | awk 'NR>1{print}')

if [[ "$__button" = "Cancel" ]]; then
  exit 0
fi

cd $1

if [[ -z "$__text" ]]; then
  __text="$__parent_branch"
fi

git fetch --tags --prune --all
git pull --rebase upstream $__text && \
git push origin $__branch -f
