#!/usr/bin/env bash
. "$(git --exec-path)/git-sh-setup"
require_clean_work_tree checkout

__cd=/Applications/CocoaDialog.app/Contents/MacOS/CocoaDialog
__out=$($__cd standard-inputbox --title "Fetch PR" --informative-text "Enter PR number" --string-output --float)
__button=$(echo "$__out" | awk 'NR==1{print}')
__text=$(echo "$__out" | awk 'NR>1{print}')

if [[ "$__button" = "Cancel" ]]; then
  exit 0
fi

cd $1

if [[ "$__button" = "Ok" && -n "$__text" ]]; then
  git fetch --force --update-head-ok upstream refs/pull/$__text/head:pr/$__text
  git checkout pr/$__text
fi
